### ISSUE TITLE
Site edits (from email)

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-pdk#1]
Creating this so you don't have to refer to your email to complete the task:

Replace this:
Growing and connecting leaders in education

With this: 
Fresno Chapter Mission: Provide regular opportunities for preK through University educators: to identify and discuss best practices; to better understand the educational continuum; and to focus on education’s role in improving our local communities. 

Current Statement on site:

Fresno Chapter PDK History

The Fresno Chapter of PDK was founded in the early 1920s. At its peak, the Fresno chapter had hundreds of active professional members. Currently, there are a handful. Currently, the Fresno Chapter is committed to meeting the needs of Fresno area educators. Will you help us? This is a unique opportunity to put your fingerprints on a local legacy.

Please copy and paste to read: 
Fresno Chapter PDK’s Story and Challenge!

The Fresno Chapter of PDK was founded in the early 1920s. At its peak, the Fresno chapter had hundreds of active professional members. Today, there are a handful. The current board asks this of every area educator: Will you help us breathe new life into the Fresno Chapter of PDK to meet the changing needs of Fresno area educators? This is a unique opportunity to put your fingerprints on a local legacy!

Currently:
Your Fresno Chapter of PDK is committed to helping eductors in any role. As the only organization that spans PreK-Higher Ed, we offer opportunities to see where your students have been and where they are expected to go. This will make your job easier and your role more effective. Join us as we join many to make the purpose of education feel good again!

Please change to read:
Your Fresno Chapter of PDK is committed to helping educators of every capacity and in every school. As the only organization that offers membership from PreK thru Higher Ed, we provide opportunities for you to see where your students have been and where they are expected to go. This will make your job easier and your role more effective. Join us to improve the lives of students of any age through education!

Due: 6-16-15  11PM  

Comment here with a new due date if you need more time.

**Comment by AaronAguilar** [comment]
It's done and live!
